services:
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
    command: ["air", "-c", "/app/.air.toml"]
    depends_on:
      - db
  backend-build:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    command: ["./main"]
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: backend_db
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    image: golang:1.24
    working_dir: /app
    volumes:
      - ./infra/db:/app
      - .env:/app/.env
    environment:
      MIGRATION_ACTION: up
    command: ["go", "run", "main.go", "${MIGRATION_ACTION}"]
    depends_on:
      - db

volumes:
  postgres_data:
